version: "3.7"
services:
    app:
        image: eu.gcr.io/judas-web/dajzekompa
        build: .
        env_file:
            - env-local.env
        environment:
            DB_URL: postgres://postgres:postgres@db:5432/dajzekompa
        ports:
            - "8080:80"
        networks:
            - dajzekompa
        depends_on:
            - db
    db:
        image: postgres:12-alpine
        environment:
            POSTGRES_DB: dajzekompa
            POSTGRES_PASSWORD: postgres
        ports:
            - "5432:5432"
        networks:
            - dajzekompa
networks:
    dajzekompa:
